### ISSUE TITLE
filtering for 'Pad/Pads' does not yield results

### ISSUE THREAD

**Issue by mhusinsky** [vvvv/The-Gray-Book#14]
... but should point to 'Properties' page.

**Comment by mhusinsky** [comment]
EDIT: sorry - the name of the issue is misleading. "searching" using the top-right search field does yield results, it's actually the "filtering" for pads that does not point to the properties page.

in general, filtering oftenly does not give expected results and the disambiguation (when to use what) between searching and filtering is not entirely clear to me.

**Comment by joreg** [comment]
the filter is really very simple. it doesn't search. it only reduces the menu-entries to those that contain your entered string.

**Comment by mhusinsky** [comment]
i see. i just checked docfx if there is some kind of tagging system that would allow to filter pages not only by the title but by some more flexible mechanism. apparently there is none which is why this issue can be closed.

UX-wise i still find this state problematic. the filtering input-field is in my opinion more prominent (top-left) and the difference between it and the search field is not clear for people not familiar with the docfx page generation system. i found myself "searching" (actually filtering) for very basic terms i knew must be in the reference, but just would not appear ("pads", "observable", "adaptive", ...). especially for language-terms of VL it would be great if filtering would work as well.

**Comment by joreg** [comment]
true, filter vs. search is confusing. and docfx unfortunately is rather unflexible. 
so what i think would actually be better for the graybook, is to remove the filter completely. search is what people most likely want.
