### ISSUE TITLE
 Shortcuts for find are missing

### ISSUE THREAD

**Issue by seltzdesign** [vvvv/The-Gray-Book#26]
I couldn't find anything on Ctrl - F, Ctrl - Shift - F and Ctrl - , I think the last two do the same thing, but its hard to tell as there is no label on the search field.

Either way they should be mentioned in the Shortcuts section.

**Comment by joreg** [comment]
documentation on finders is here: https://thegraybook.vvvv.org/reference/hde/finders.html
and just now added to the shortcuts page. thanks for pointing this out.
